FROM node:24-alpine AS build
WORKDIR /app
COPY vite/package.json vite/yarn.lock ./
RUN yarn install --frozen-lockfile
COPY vite/ ./
RUN yarn build

FROM nginx:alpine
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
